config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  devise_for :users, controllers: { registrations: "users/registrations" }

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/*
  get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker
  get "manifest" => "rails/pwa#manifest", as: :pwa_manifest

  # Defines the root path route ("/")
  root "books#index"

  resources :books, only: [ :show ] do
    resources :reviews, only: [ :new, :create, :edit, :update ], module: :books
  end

  resources :reviews, only: [] do
    member do
      post "vote-toggle-like", to: "votes#toggle_vote", defaults: { vote_type: "like" }, as: :toggle_like
      post "vote-toggle-dislike", to: "votes#toggle_vote", defaults: { vote_type: "dislike" }, as: :toggle_dislike
    end
  end

  scope "profile" do
    get "/", to: "profiles#show", as: :profile
    resources :reviews, only: [ :edit, :update ], module: :profiles, as: :profile_reviews
  end
end

app/models/book.rb
class Book < ApplicationRecord
  include PgSearch::Model
  include ImageUploadable

  has_many :reviews, dependent: :destroy

  validates :title, presence: true

  before_validation :normalize_fields

  pg_search_scope :search_books,
                  using: {
                    tsearch: {
                      dictionary: "english",
                      tsvector_column: "textsearchable_col"
                    }
                  }

  def cache_ratings_average
    update ratings_avg: reviews.average(:rating)
  end

  def rating_statistics
    counter = reviews.group(:rating).count
    return if counter.blank?

    total = counter.values.sum
    statistics = { total: total }

    (1..5).each do |rating|
      count = counter[rating] || 0
      percentage = total.zero? ? 0 : ((count.to_f / total) * 100).round
      statistics["rating_#{rating}".to_sym] = { rating: rating, count: count, perc: percentage }
    end

    statistics
  end

  private

  def normalize_fields
    self.title = title.try(:squish)
    self.subtitle = subtitle.try(:squish)
  end
end

app/controllers/books/reviews_controller.rb
class Books::ReviewsController < ReviewsController
  include FindBook

  def new
    @review = @book.reviews.new
  end

  def create
    @review = @book.reviews.new(review_params)
    @review.user = current_user

    if @review.save
      @book.cache_ratings_average
      respond_to do |format|
        format.html { redirect_to book_path(@book) }
        format.turbo_stream
      end
    else
      render :new, status: :unprocessable_entity
    end
  end

  private

  def after_update_path
    book_path(@book)
  end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  include Pagy::Backend
  include FindBook

  before_action :find_book, only: [ :show ]

  def index
    if params[:query].present?
      @books = Book.search_books(params[:query])
    else
      @books = Book.all
    end

    @books = @books.with_attached_image
    @pagy, @books = pagy(@books)
  end

  def show
    @reviews = @book.reviews
    rating = params[:rating].to_i
    if rating.between?(1, 5)
      @reviews = @reviews.where(rating: rating)
      @filtered = true
    end
    @reviews = @reviews.ordered.eager_load(:user, :votes)

    @pagy, @reviews = pagy(@reviews)
  end
end

app/helpers/books/reviews_helper.rb
module Books::ReviewsHelper
  def rating_field(f)
    content_tag :div, class: "flex flex-row-reverse justify-end items-center" do
      (1..5).reverse_each.map do |rating|
        f.radio_button(:rating, rating, class: "peer -ms-5 size-5 bg-transparent border-0 text-transparent cursor-pointer appearance-none checked:bg-none focus:bg-none focus:ring-0 focus:ring-offset-0") +
        f.label("rating_#{rating}", class: "peer-checked:text-yellow-400 text-gray-300 pointer-events-none") do
          inline_svg_tag("star.svg", class: "size-6 shrink-0")
        end
      end.join.html_safe
    end
  end

  def user_is_creator?(review)
    review.user_id == current_user&.id
  end
end

app/helpers/books_helper.rb
module BooksHelper
  def book_image(book, classes = "")
    return unless book.image.attached?

    image_tag book.image.variant(:small),
              class: classes,
              alt: book.title,
              loading: "lazy"
  end
end

app/views/books/_book.html.erb
<div class="group">
  <%= link_to book_path(book), class: "flex flex-col items-center" do %>
    <div class="relative overflow-hidden rounded shadow-md transition duration-300 ease-in-out group-hover:shadow-xl bg-white">
      <%= book_image(book, "w-full h-72 object-cover transition duration-300 ease-in-out group-hover:scale-105") %>
      <div class="absolute inset-0 bg-gradient-to-t from-black/60 to-transparent opacity-0 group-hover:opacity-100 transition duration-300 ease-in-out"></div>
    </div>
    <h3 class="mt-3 px-2 text-center text-sm font-medium leading-tight text-gray-800 group-hover:text-blue-600 transition duration-300 ease-in-out line-clamp-2"><%= book.title %></h3>
  <% end %>
</div>

app/views/books/_books.html.erb
<div class="grid grid-cols-2 sm:grid-cols-3 lg:grid-cols-4 xl:grid-cols-5 gap-6 lg:gap-8">
  <%= render @books %>
</div>

<%== pagy_nav(@pagy) if @pagy.pages > 1 %>

app/views/books/_empty_list.html.erb
<h1 class="text-3xl text-center mt-8">No books found :(</h1>
<p class="text-center mt-2">
  Please try a different query or <%= link_to "return to all books", root_path, class: "underline" %>
</p>

app/views/books/_rating_statistics_box.html.erb
<%# locals(book:) %>

<% statistics = book.rating_statistics %>
<% if statistics.present? %>
  <div class="bg-white rounded-lg shadow-md p-6 mb-12" id="rating-statistics">
    <div class="flex items-center space-x-4 mb-4">
      <div class="flex space-x-1">
        <%= render_stars(book.ratings_avg.round, "size-5 text-yellow-500") %>
      </div>
      <p class="text-2xl font-semibold text-gray-900"><%= book.ratings_avg %></p>
      <p class="text-gray-600">(<%= pluralize(statistics[:total], "review") %>)</p>
    </div>
    <div class="space-y-2">
      <% (1..5).reverse_each.map do |i| %>
        <% statistic = statistics["rating_#{i}".to_sym] %>
        <div class="flex items-center space-x-2">
          <%= link_to pluralize(i, "star"), book_path(book, page: params[:page], rating: i), class: "text-sm font-medium w-16 underline hover:no-underline" %>
          <div class="flex-grow bg-gray-200 rounded-full h-2">
            <div class="bg-yellow-500 h-2 rounded-full" style="width: <%= statistic[:perc] %>%;"></div>
          </div>
          <span class="text-sm text-gray-600 w-24 text-right">
            <%= statistic[:count] %> (<%= statistic[:perc] %>%)
          </span>
        </div>
      <% end %>
    </div>
  </div>
<% end %>

app/views/books/index.html.erb
<% content_for :header do %>
  <div class="flex-grow mx-4 max-w-3xl">
    <%= form_with url: request.path, method: :get, class: "relative", data: { turbo_frame: "listing", turbo_action: "advance" } do %>
      <%= text_field_tag :query, params[:query], autocomplete: "off", placeholder: "Search books...", class: "w-full py-2 px-4 bg-gray-100 border-2 border-gray-200 text-gray-800 rounded-full focus:outline-none focus:ring-2 focus:ring-blue-400 focus:border-transparent transition duration-150" %>
      <%= button_tag type: "submit", name: nil, class: "absolute inset-y-0 right-0 flex items-center pr-4" do %>
        <%= inline_svg_tag("search.svg", class: "w-5 h-5 text-gray-500 hover:text-blue-500 transition duration-150") %>
      <% end %>
    <% end %>
  </div>
<% end %>

<div class="container mx-auto mt-8 px-4 lg:px-6 pb-8 lg:pb-12">
  <%= turbo_frame_tag "listing", target: "_top" do %>
    <% if @books.blank? %>
      <%= render partial: "empty_list" %>
    <% else %>
      <%= render partial: "books" %>
    <% end %>
  <% end %>
</div>

app/views/books/show.html.erb
<%= turbo_stream_from @book %>
<% content_for :aside do %>
  <%= book_image(@book, "w-auto max-w-full mx-auto rounded shadow-lg transition duration-300 hover:shadow-xl") %>
  <% if user_signed_in? %>
    <%= link_to "Leave a review", new_book_review_path(@book), class: "mt-6 px-8 py-2 inline-flex items-center justify-center border border-transparent text-base font-medium rounded-md text-white bg-blue-600 hover:bg-blue-700 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-blue-500 transition duration-150", data: { turbo_frame: "modal" } %>
  <% end %>
<% end %>

<%= render "shared/two_column_layout" do %>
  <header>
    <h1 class="text-4xl font-bold text-gray-900 mb-2"><%= @book.title %></h1>
    <p class="text-2xl text-gray-700 italic mb-8"><%= @book.subtitle %></p>
  </header>

  <%= render partial: "rating_statistics_box", locals: { book: @book} %>

  <section>
    <header>
      <h2 class="text-3xl font-semibold text-gray-900 pb-2 border-b-2 border-gray-200">Reviews</h2>
    </header>

    <% if @reviews.any? %>
      <% if @filtered %>
        <p class="text-gray-600 text-lg mt-6">
          You're viewing <%= pluralize(params[:rating], "star") %> reviews.
          <%= link_to "View all", book_path(@book), class: "underline" %>.
        </p>
      <% end %>

      <div id="reviews-list">
        <%= render partial: "books/reviews/review", collection: @reviews %>
      </div>

      <% if @pagy.pages > 1 %>
        <div class="mt-8">
          <%== pagy_nav(@pagy) %>
        </div>
      <% end %>

    <% else %>
      <% if @filtered %>
        <p class="text-gray-600 text-lg mt-6" id="empty-reviews-message">
          No <%= pluralize(params[:rating], "star") %> reviews found.
          <%= link_to "View all", book_path(@book), class: "underline" %>.
        </p>
      <% else %>
        <p class="text-gray-600 text-lg mt-6" id="empty-reviews-message">
          No reviews yet. Be the first to leave a review!
        </p>
      <% end %>
    <% end %>
  </section>
<% end %>