config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  devise_for :users, controllers: { registrations: "users/registrations" }

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/*
  get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker
  get "manifest" => "rails/pwa#manifest", as: :pwa_manifest

  # Defines the root path route ("/")
  root "books#index"

  resources :books, only: [ :show ] do
    resources :reviews, only: [ :new, :create, :edit, :update ], module: :books
  end

  resources :reviews, only: [] do
    member do
      post "vote-toggle-like", to: "votes#toggle_vote", defaults: { vote_type: "like" }, as: :toggle_like
      post "vote-toggle-dislike", to: "votes#toggle_vote", defaults: { vote_type: "dislike" }, as: :toggle_dislike
    end
  end

  scope "profile" do
    get "/", to: "profiles#show", as: :profile
    resources :reviews, only: [ :edit, :update ], module: :profiles, as: :profile_reviews
  end
end

app/controllers/books/reviews_controller.rb
class Books::ReviewsController < ReviewsController
  include FindBook

  def new
    @review = @book.reviews.new
  end

  def create
    @review = @book.reviews.new(review_params)
    @review.user = current_user

    if @review.save
      @book.cache_ratings_average
      respond_to do |format|
        format.html { redirect_to book_path(@book) }
        format.turbo_stream
      end
    else
      render :new, status: :unprocessable_entity
    end
  end

  private

  def after_update_path
    book_path(@book)
  end
end

app/controllers/profiles/reviews_controller.rb
class Profiles::ReviewsController < ReviewsController
  private

  def after_update_path
    profile_path
  end
end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController
  include Pagy::Backend
  before_action :authenticate_user!

  def show
    @reviews = current_user.reviews.ordered.eager_load(:book)
    @pagy, @reviews = pagy(@reviews)
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  include FindReview

  before_action :authenticate_user!
  before_action :find_review, only: [ :edit, :update ]
  before_action :authorize_user, only: [ :edit, :update ]

  def edit
  end

  def update
    if @review.update(review_params)
      @review.book.cache_ratings_average
      respond_to do |format|
        format.html { redirect_to(after_update_path) }
        format.turbo_stream
      end
    else
      render :edit, status: :unprocessable_entity
    end
  end

  private

  def review_params
    params.require(:review).permit(:title, :description, :rating)
  end

  def authorize_user
    unless @review.user_id == current_user.id
      redirect_to root_path
    end
  end

  # This method should be overridden in child controllers
  def after_update_path
    raise NotImplementedError, "#{self.class} must implement #after_update_path"
  end
end

app/helpers/books/reviews_helper.rb
module Books::ReviewsHelper
  def rating_field(f)
    content_tag :div, class: "flex flex-row-reverse justify-end items-center" do
      (1..5).reverse_each.map do |rating|
        f.radio_button(:rating, rating, class: "peer -ms-5 size-5 bg-transparent border-0 text-transparent cursor-pointer appearance-none checked:bg-none focus:bg-none focus:ring-0 focus:ring-offset-0") +
        f.label("rating_#{rating}", class: "peer-checked:text-yellow-400 text-gray-300 pointer-events-none") do
          inline_svg_tag("star.svg", class: "size-6 shrink-0")
        end
      end.join.html_safe
    end
  end

  def user_is_creator?(review)
    review.user_id == current_user&.id
  end
end

app/helpers/profiles/reviews_helper.rb
module Profiles::ReviewsHelper
end

app/helpers/profiles_helper.rb
module ProfilesHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
  def render_stars(rating, class_name = "size-4", max_stars = 5)
    full_stars = [ inline_svg_tag("star.svg", class: class_name) * rating ]
    empty_stars = [ inline_svg_tag("star-outline.svg", class: class_name) * (max_stars - rating) ]

    content_tag :span, class: "flex" do
      safe_join(full_stars + empty_stars)
    end
  end
end

app/views/profiles/reviews/_review.html.erb
<%# locals: (review:) -%>

<%= content_tag :div, class: "border-b border-gray-200 py-6", id: dom_id(review) do %>
  <div class="flex justify-between items-start">
    <div>
      <h3 class="text-lg font-semibold text-gray-800"><%= review.book.title %></h3>
      <div class="mt-1">
        <%= render_stars(review.rating) %>
      </div>
    </div>
    <%= link_to edit_profile_review_path(review), class: "text-gray-400 hover:text-blue-600 transition duration-150", data: { turbo_frame: "modal" } do %>
      <%= inline_svg_tag("pencil-square.svg", class: "w-5 h-5") %>
    <% end %>
  </div>
  <h4 class="text-md font-medium text-gray-700 mt-4"><%= review.title %></h4>
  <p class="text-gray-700"><%= review.description %></p>
  <%= link_to "View Book", book_path(review.book), class: "mt-2 inline-block text-sm text-blue-600 hover:text-blue-800 transition" %>
<% end %>

app/views/profiles/reviews/edit.html.erb
<%= render partial: "reviews/form", locals: { url: profile_review_path(@review), submit_label: "Update review" } %>

app/views/profiles/reviews/update.turbo_stream.erb
<%= turbo_stream.replace(dom_id(@review), partial: "review", locals: { review: @review }) %>