config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  devise_for :users, controllers: { registrations: "users/registrations" }

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/*
  get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker
  get "manifest" => "rails/pwa#manifest", as: :pwa_manifest

  # Defines the root path route ("/")
  root "books#index"

  resources :books, only: [ :show ] do
    resources :reviews, only: [ :new, :create, :edit, :update ], module: :books
  end

  resources :reviews, only: [] do
    member do
      post "vote-toggle-like", to: "votes#toggle_vote", defaults: { vote_type: "like" }, as: :toggle_like
      post "vote-toggle-dislike", to: "votes#toggle_vote", defaults: { vote_type: "dislike" }, as: :toggle_dislike
    end
  end

  scope "profile" do
    get "/", to: "profiles#show", as: :profile
    resources :reviews, only: [ :edit, :update ], module: :profiles, as: :profile_reviews
  end
end

app/models/book.rb
class Book < ApplicationRecord
  include PgSearch::Model
  include ImageUploadable

  has_many :reviews, dependent: :destroy

  validates :title, presence: true

  before_validation :normalize_fields

  pg_search_scope :search_books,
                  using: {
                    tsearch: {
                      dictionary: "english",
                      tsvector_column: "textsearchable_col"
                    }
                  }

  def cache_ratings_average
    update ratings_avg: reviews.average(:rating)
  end

  def rating_statistics
    counter = reviews.group(:rating).count
    return if counter.blank?

    total = counter.values.sum
    statistics = { total: total }

    (1..5).each do |rating|
      count = counter[rating] || 0
      percentage = total.zero? ? 0 : ((count.to_f / total) * 100).round
      statistics["rating_#{rating}".to_sym] = { rating: rating, count: count, perc: percentage }
    end

    statistics
  end

  private

  def normalize_fields
    self.title = title.try(:squish)
    self.subtitle = subtitle.try(:squish)
  end
end

app/controllers/books/reviews_controller.rb
class Books::ReviewsController < ReviewsController
  include FindBook

  def new
    @review = @book.reviews.new
  end

  def create
    @review = @book.reviews.new(review_params)
    @review.user = current_user

    if @review.save
      @book.cache_ratings_average
      respond_to do |format|
        format.html { redirect_to book_path(@book) }
        format.turbo_stream
      end
    else
      render :new, status: :unprocessable_entity
    end
  end

  private

  def after_update_path
    book_path(@book)
  end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  include Pagy::Backend
  include FindBook

  before_action :find_book, only: [ :show ]

  def index
    if params[:query].present?
      @books = Book.search_books(params[:query])
    else
      @books = Book.all
    end

    @books = @books.with_attached_image
    @pagy, @books = pagy(@books)
  end

  def show
    @reviews = @book.reviews
    rating = params[:rating].to_i
    if rating.between?(1, 5)
      @reviews = @reviews.where(rating: rating)
      @filtered = true
    end
    @reviews = @reviews.ordered.eager_load(:user, :votes)

    @pagy, @reviews = pagy(@reviews)
  end
end

app/controllers/profiles/reviews_controller.rb
class Profiles::ReviewsController < ReviewsController
  private

  def after_update_path
    profile_path
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  include FindReview

  before_action :authenticate_user!
  before_action :find_review, only: [ :edit, :update ]
  before_action :authorize_user, only: [ :edit, :update ]

  def edit
  end

  def update
    if @review.update(review_params)
      @review.book.cache_ratings_average
      respond_to do |format|
        format.html { redirect_to(after_update_path) }
        format.turbo_stream
      end
    else
      render :edit, status: :unprocessable_entity
    end
  end

  private

  def review_params
    params.require(:review).permit(:title, :description, :rating)
  end

  def authorize_user
    unless @review.user_id == current_user.id
      redirect_to root_path
    end
  end

  # This method should be overridden in child controllers
  def after_update_path
    raise NotImplementedError, "#{self.class} must implement #after_update_path"
  end
end

app/helpers/books/reviews_helper.rb
module Books::ReviewsHelper
  def rating_field(f)
    content_tag :div, class: "flex flex-row-reverse justify-end items-center" do
      (1..5).reverse_each.map do |rating|
        f.radio_button(:rating, rating, class: "peer -ms-5 size-5 bg-transparent border-0 text-transparent cursor-pointer appearance-none checked:bg-none focus:bg-none focus:ring-0 focus:ring-offset-0") +
        f.label("rating_#{rating}", class: "peer-checked:text-yellow-400 text-gray-300 pointer-events-none") do
          inline_svg_tag("star.svg", class: "size-6 shrink-0")
        end
      end.join.html_safe
    end
  end

  def user_is_creator?(review)
    review.user_id == current_user&.id
  end
end

app/helpers/books_helper.rb
module BooksHelper
  def book_image(book, classes = "")
    return unless book.image.attached?

    image_tag book.image.variant(:small),
              class: classes,
              alt: book.title,
              loading: "lazy"
  end
end

app/helpers/profiles/reviews_helper.rb
module Profiles::ReviewsHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
  def render_stars(rating, class_name = "size-4", max_stars = 5)
    full_stars = [ inline_svg_tag("star.svg", class: class_name) * rating ]
    empty_stars = [ inline_svg_tag("star-outline.svg", class: class_name) * (max_stars - rating) ]

    content_tag :span, class: "flex" do
      safe_join(full_stars + empty_stars)
    end
  end
end

app/views/books/reviews/_form.html.erb
<%# locals: (url:, submit_label:) -%>

<%= modal({title: "Review: #{@book.title}"}) do %>
  <%= modal_form_for(@review, url: url) do |f| %>
    <%= alert_error(@review.errors.full_messages) %>

    <div class="field">
      <%= f.label :rating %>
      <%= rating_field(f) %>
    </div>

    <div class="field">
      <%= f.label :title %>
      <%= f.text_field :title, autofocus: true %>
    </div>

    <div class="field">
      <%= f.label :description %>
      <%= f.text_area :description %>
    </div>

    <div class="actions">
      <%= f.submit submit_label %>
    </div>
  <% end %>
<% end %>

app/views/books/reviews/_review.html.erb
<%# locals: (review:) -%>

<%= content_tag :div, class: "border-b border-gray-200 py-8", id: dom_id(review) do %>
  <div class="flex justify-between items-start">
    <div class="space-y-1">
      <%= render_stars(review.rating) %>
      <h3 class="text-xl font-semibold text-gray-800"><%= review.title %></h3>
      <p class="text-sm text-gray-500">By <%= review.user.nickname %></p>
    </div>
    <% if user_is_creator?(review) %>
      <%= link_to edit_book_review_path(@book, review), class: "text-gray-400 hover:text-blue-600 transition duration-150", data: { turbo_frame: "modal" } do %>
        <%= inline_svg_tag("pencil-square.svg", class: "w-6 h-6") %>
      <% end %>
    <% end %>
  </div>
  <p class="text-gray-600 mt-4"><%= review.description %></p>

  <div class="flex items-center space-x-6 mt-4">
    <%= vote_button("like", review) %>
    <%= vote_button("dislike", review) %>
  </div>
<% end %>

app/views/books/reviews/create.turbo_stream.erb
<%= turbo_stream.prepend("reviews-list", partial: "review", locals: { review: @review }) %>
<%= turbo_stream.replace("rating-statistics", partial: "books/rating_statistics_box", locals: { book: @book }) %>
<%= turbo_stream.replace("empty-reviews-message") do %>
 <% # In the case this is the first review we need to replace the "empty-reviews-message" element %>
  <div id="reviews-list">
    <%= render partial: "review", locals: { review: @review } %>
  </div>
<% end %>

app/views/books/reviews/edit.html.erb
<%= render partial: "reviews/form", locals: { url: book_review_path(@book, @review), submit_label: "Update review" } %>

app/views/books/reviews/new.html.erb
<%= render partial: "reviews/form", locals: { url: book_reviews_path, submit_label: "Leave review" } %>

app/views/books/reviews/update.turbo_stream.erb
<%= turbo_stream.replace(dom_id(@review), partial: "review", locals: { review: @review }) %>
<%= turbo_stream.replace("rating-statistics", partial: "books/rating_statistics_box", locals: { book: @book }) %>